### ISSUE TITLE
Zła ścieżka do tank_motion.js

### ISSUE THREAD

**Issue by dyedmagenta** [ZuzannaZawartka/Tank-motion-system#1]
Po zaciągnięciu projektu do pliku jest podana zła ścieżka zamiast `src="tank_motion.js"` jest `src="/tank_motion.js"`.
Co powoduje że czołgu się nie odpala a na konsolce pojawia się taki błąd:
![obraz](https://user-images.githubusercontent.com/16865216/141147263-5b73ce31-bc5a-4782-a762-b48c8b4dd908.png)

---
Natomiast całość po poprawieniu ścieżku bangla i ogólnie jak dla mnie jest spoko 👌

**Comment by ZuzannaZawartka** [comment]
Dzięki, błąd poprawiony.
